Fix exception when executing empty SQL on PHP 8
When calling execute() with an empty SQL query on MySQL, PHP throws an
Exception:

ValueError: mysqli_query(): Argument #2 ($query) cannot be empty

We now check that $sql is not empty, and if it is just return false.

Fixes #945

Back-ported from commit 8c57976eaf2f4cf9a71cc7fb88edb1d7b90b00ce.

# Conflicts:
#	drivers/adodb-mysqli.inc.php