Fix exception in announce.py
The announcement script triggered an exception:
AttributeError: 'NoneType' object has no attribute 'tagged_date'

This was caused by a local lightweight tag, which has no associated
attributes so the lambda function used to sort the tags chronologically
crashed attempting to access non-existing 'tagged_date'.

Lambda was modified to return 0 in this case.