Remove '\n' from Exception messages
Messages with newline cause uncaught exceptions to be displayed as
follows (note the single ' where the message is expected):

$ php -r 'throw new exception("blah\n");'

Fatal error: Uncaught exception 'Exception' with message ' in Command line code on line 1