Fix PHP ERROR: Uncaught ArgumentCountError
Too few arguments to function ADORecordSet_array::__construct(), 0
passed in adodb/adodb-csvlib.inc.php on line 79 and at least 1 expected.

Regression introduced by 57186f905c9a1e49a010daf582baa9a07be826bb

Fixes #772 (see PR #785)

Signed-off-by: Damien Regad <dregad@mantisbt.org>